### ISSUE TITLE
User having issue with modded race

### ISSUE THREAD

**Issue by Fevix** [zimberzimber/Ztarbound#1]
Avali-Triage-Team/Avali#396

A user is trying to use Ztarbound with the Avali race, but it doesn't seem to be working. The SAIL interface is aparrently unresponsive. A log has been requested from the user.

**Comment by jtgibson01** [comment]
Looks like his log is having trouble with a mod called "Avali Drone Pet".  When SAIL tries to spawn that monster, the techstation.lua sends a crash.

**Comment by xn-5o8h** [comment]
That's an issue I had with some outdated pets ( https://steamcommunity.com/sharedfiles/filedetails/?id=952185344 , https://steamcommunity.com/sharedfiles/filedetails/?id=950790322 )

**Comment by zimberzimber** [comment]
Issue seems unrelated to FU/ZB
The log points to a vanilla file thats 96 lines long, and the error is said to be at line 151
Said file is untouched by FU/ZB
